INSERT INTO post
(
    slug,
    author,
    title,
    perex,
    body,
    published
) VALUES
(
    'anti-americans-abroad',
    'Tony Judt',
    'Anti-Americans Abroad',
    '<header><p>If you want to understand how America appears to the world today, consider the sport-utility vehicle</p></header>',
    '<section><p>' ||
    'It consumes inordinate quantities of scarce resources to furnish its privileged inhabitants with supererogatory services. It exposes outsiders to deadly risk in order to provide for the illusory security of its occupants. In a crowded world, the SUV appears as a dangerous anachronism. Like US foreign policy, the sport-utility vehicle comes packaged in sonorous mission statements; but underneath it is just an oversized pickup truck with too much power.' ||
    '</p><p>' ||
    'The simile may be modern, but the idea behind it is not. “America” has been an object of foreign suspicion for even longer than it has been a beacon and haven for the world’s poor and downtrodden. Eighteenth-century commentators—on the basis of very little direct observation—believed America’s flora and fauna to be stunted, and of limited interest or use. The country could never be civilized, they insisted, and much the same was true of its unso- phisticated new citizens. As the French diplomat (and bishop) Talleyrand observed, anticipating two centuries of European commentary: “Trente-deux réligions et un seul plat” (“thirty-two religions and just one dish”—which Americans typically and understandably tended to eat in a hurry). From the perspective of a cosmopolitan European conservative like Joseph de Maistre, writing in the early years of the nineteenth century, the US was a regrettable aberration — and too crude to endure for long.' ||
    '</p><p>' ||
    'Charles Dickens, like Alexis de Tocqueville, was struck by the conformism of American public life. Stendhal commented upon the country’s “egoism”; Baudelaire sniffily compared it to Belgium (!) in its bourgeois mediocrity; everyone remarked upon the jejune patriotic pomp of the US. But in the course of the next century, European commentary shifted perceptibly from the dismissive to the resentful. By the 1930s, the United States’ economic power was giving a threatening twist to its crude immaturity. For a new generation of anti-democratic critics, the destabilizing symptoms of modern life—mass production, mass society, and mass politics—could all be traced to America.' ||
    '</p></section>' ||
    '<footer>' ||
    'Tony Judt (1948–2010) was the founder and director of the Remarque Institute at NYU and the author of <i>Postwar: A History of Europe Since 1945</i>, <i>Ill Fares the Land</i>, and <i>The Burden of Responsibility: Blum, Camus, Aron, and the French Twentieth Century</i>, among other books.' ||
    '</footer>',
    '2021-05-27'
),
(
    'israel-the-alternative',
    'Tony Judt',
    'Israel: The Alternative',
    '<header><p>The Middle East peace process is finished. It did not die: it was killed.</p></header>',
    '<section><p>' ||
    'Mahmoud Abbas was undermined by the President of the Palestinian Authority and humiliated by the Prime Minister of Israel. His successor awaits a similar fate. Israel continues to mock its American patron, building illegal settlements in cynical disregard of the “road map.” The President of the United States of America has been reduced to a ventriloquist’s dummy, pitifully reciting the Israeli cabinet line: “It’s all Arafat’s fault.” Israelis themselves grimly await the next bomber. Palestinian Arabs, corralled into shrinking Bantustans, subsist on EU handouts. On the corpse-strewn landscape of the Fertile Crescent, Ariel Sharon, Yasser Arafat, and a handful of terrorists can all claim victory, and they do. Have we reached the end of the road? What is to be done?' ||
    '</p><p>' ||
    'At the dawn of the twentieth century, in the twilight of the continental empires, Europe’s subject peoples dreamed of forming “nation-states,” territorial homelands where Poles, Czechs, Serbs, Armenians, and others might live free, masters of their own fate. When the Habsburg and Romanov empires collapsed after World War I, their leaders seized the opportunity. A flurry of new states emerged; and the first thing they did was set about privileging their national, “ethnic” majority—defined by language, or religion, or antiquity, or all three—at the expense of inconvenient local minorities, who were consigned to second-class status: permanently resident strangers in their own home.' ||
    '</p><p>' ||
    'But one nationalist movement, Zionism, was frustrated in its ambitions. The dream of an appropriately sited Jewish national home in the middle of the defunct Turkish Empire had to wait upon the retreat of imperial Britain: a process that took three more decades and a second world war. And thus it was only in 1948 that a Jewish nation-state was established in formerly Ottoman Palestine. But the founders of the Jewish state had been influenced by the same concepts and categories as their fin-de-siècle contemporaries back in Warsaw, or Odessa, or Bucharest; not surprisingly, Israel’s ethno-religious self-definition, and its discrimination against internal “foreigners,” has always had more in common with, say, the practices of post-Habsburg Romania than either party might care to acknowledge.' ||
    '</p><p>' ||
    'The problem with Israel, in short, is not—as is sometimes suggested—that it is a European “enclave” in the Arab world; but rather that it arrived too late. It has imported a characteristically late-nineteenth-century separatist project into a world that has moved on, a world of individual rights, open frontiers, and international law. The very idea of a “Jewish state”—a state in which Jews and the Jewish religion have exclusive privileges from which non-Jewish citizens are forever excluded—is rooted in another time and place. Israel, in short, is an anachronism.' ||
    '</p><p>' ||
    'In one vital attribute, however, Israel is quite different from previous insecure, defensive microstates born of imperial collapse: it is a democracy. Hence its present dilemma. Thanks to its occupation of the lands conquered in 1967, Israel today faces three unattractive choices. It can dismantle the Jewish settlements in the territories, return to the 1967 state borders within which Jews constitute a clear majority, and thus remain both a Jewish state and a democracy, albeit one with a constitutionally anomalous community of second-class Arab citizens.' ||
    '</p></section>' ||
    '<footer>' ||
    'Tony Judt (1948–2010) was the founder and director of the Remarque Institute at NYU and the author of <i>Postwar: A History of Europe Since 1945</i>, <i>Ill Fares the Land</i>, and <i>The Burden of Responsibility: Blum, Camus, Aron, and the French Twentieth Century</i>, among other books.' ||
    '</footer>',
    '2021-05-28'
),
(
    'israel-without-cliches',
    'Tony Judt',
    'Israel Without Clichés',
    '<header><p>The Israeli raid on the Free Gaza flotilla has generated an outpouring of clichés from the usual suspects</p></header>',
    '<section><p>' ||
    'It is almost impossible to discuss the Middle East without resorting to tired accusations and ritual defenses: perhaps a little house cleaning is in order.' ||
    '</p><p>' ||
    'Israel is a state like any other, long-established and internationally recognized. The bad behavior of its governments does not “delegitimize” it, any more than the bad behavior of the rulers of North Korea, Sudan — or, indeed, the United States — “delegitimizes” them. When Israel breaks international law, it should be pressed to desist; but it is precisely because it is a state under international law that we have that leverage.' ||
    '</p><p>' ||
    'Some critics of Israel are motivated by a wish that it did not exist — that it would just somehow go away. But this is the politics of the ostrich: Flemish nationalists feel the same way about Belgium, Basque separatists about Spain. Israel is not going away, nor should it. As for the official Israeli public relations campaign to discredit any criticism as an exercise in “de-legitimization,” it is uniquely self-defeating. Every time Jerusalem responds this way, it highlights its own isolation.' ||
    '</p><p>' ||
    'Perhaps the most common defense of Israel outside the country is that it is “the only democracy in the Middle East.” This is largely true: the country has an independent judiciary and free elections, though it also discriminates against non-Jews in ways that distinguish it from most other democracies today. The expression of strong dissent from official policy is increasingly discouraged.' ||
    '</p><p>' ||
    'But the point is irrelevant.  “Democracy”  is no guarantee of good behavior: most countries today are formally democratic — remember Eastern Europe’s “popular democracies.” Israel belies the comfortable American cliché that “democracies don’t make war.” It is a democracy dominated and often governed by former professional soldiers: this alone distinguishes it from other advanced countries. And we should not forget that Gaza is another “democracy” in the Middle East: it was precisely because Hamas won free elections there in 2005 that both the Palestinian Authority and Israel reacted with such vehemence.' ||
    '</p><p>' ||
    'Israel is not responsible for the fact that many of its near neighbors long denied its right to exist. The sense of siege should not be underestimated when we try to understand the delusional quality of many Israeli pronouncements. Unsurprisingly, the state has acquired pathological habits. Of these, the most damaging is its habitual resort to force. Because this worked for so long — the easy victories of the country’s early years are ingrained in folk memory — Israel finds it difficult to conceive of other ways to respond. And the failure of the negotiations of 2000 at Camp David reinforced the belief that “there is no one to talk to.”' ||
    '</p><p>' ||
    'But there is. As American officials privately acknowledge, sooner or later Israel (or someone) will have to talk to Hamas. From French Algeria through South Africa to the Provisional I.R.A., the story repeats itself: the dominant power denies the legitimacy of the “terrorists,” thereby strengthening their hand; then it secretly negotiates with them; finally, it concedes power, independence or a place at the table. Israel will negotiate with Hamas: the only question is why not now.' ||
    '</p><p>' ||
    'Abba Eban, the former Israeli foreign minister, claimed that Arabs never miss an opportunity to miss an opportunity. He was not wholly wrong. The “negationist” stance of Palestinian resistance movements from 1948 through the early 1980s did them little good. And Hamas, firmly in that tradition though far more genuinely popular than its predecessors, will have to acknowledge Israel’s right to exist.' ||
    '</p><p>' ||
    'But since 1967 it has been Israel that has missed most opportunities: a 40-year occupation (against the advice of its own elder statesmen); three catastrophic invasions of Lebanon; an invasion and blockade of Gaza in the teeth of world opinion; and now a botched attack on civilians in international waters. Palestinians would be hard put to match such cumulative blunders.' ||
    '</p><p>' ||
    'Terrorism is the weapon of the weak — bombing civilian targets was not invented by Arabs (nor by the Jews who engaged in it before 1948). Morally indefensible, it has characterized resistance movements of all colors for at least a century. Israelis are right to insist that any talks or settlements will depend upon Hamas’s foreswearing it.' ||
    '</p><p>' ||
    'But Palestinians face the same conundrum as every other oppressed people: all they have with which to oppose an established state with a monopoly of power is rejection and protest. If they pre-concede every Israeli demand — abjurance of violence, acceptance of Israel, acknowledgment of all their losses — what do they bring to the negotiating table? Israel has the initiative: it should exercise it.' ||
    '</p><p>' ||
    'There is an Israel lobby in Washington and it does a very good job — that’s what lobbies are for. Those who claim that the Israel lobby is unfairly painted as “too influential” (with the subtext of excessive Jewish influence behind the scenes) have a point: the gun lobby, the oil lobby and the banking lobby have all done far more damage to the health of this country.' ||
    '</p><p>' ||
    'But the Israel lobby is disproportionately influential. Why else do an overwhelming majority of congressmen roll over for every pro-Israel motion? No more than a handful show consistent interest in the subject. It is one thing to denounce the excessive leverage of a lobby, quite another to accuse Jews of “running the country.” We must not censor ourselves lest people conflate the two. In Arthur Koestler’s words, “This fear of finding oneself in bad company is not an expression of political purity; it is an expression of a lack of self-confidence.”' ||
    '</p><p>' ||
    'Anti-Semitism is hatred of Jews, and Israel is a Jewish state, so of course some criticism of it is malevolently motivated. There have been occasions in the recent past (notably in the Soviet Union and its satellites) when “anti-Zionism” was a convenient surrogate for official anti-Semitism. Understandably, many Jews and Israelis have not forgotten this.' ||
    '</p><p>' ||
    'But criticism of Israel, increasingly from non-Israeli Jews, is not predominantly motivated by anti-Semitism. The same is true of contemporary anti-Zionism: Zionism itself has moved a long way from the ideology of its “founding fathers” — today it presses territorial claims, religious exclusivity and political extremism. One can acknowledge Israel’s right to exist and still be an anti-Zionist (or “post-Zionist”). Indeed, given the emphasis in Zionism on the need for the Jews to establish a “normal state” for themselves, today’s insistence on Israel’s right to act in “abnormal” ways because it is a Jewish state suggests that Zionism has failed.' ||
    '</p><p>' ||
    'We should beware the excessive invocation of “anti-Semitism.” A younger generation in the United States, not to mention worldwide, is growing skeptical. “If criticism of the Israeli blockade of Gaza is potentially ‘anti-Semitic,’ why take seriously other instances of the prejudice?” they ask, and “What if the Holocaust has become just another excuse for Israeli bad behavior?” The risks that Jews run by encouraging this conflation should not be dismissed.' ||
    '</p><p>' ||
    'Along with the oil sheikdoms, Israel is now America’s greatest strategic liability in the Middle East and Central Asia. Thanks to Israel, we are in serious danger of “losing” Turkey: a Muslim democracy, offended at its treatment by the European Union, that is the pivotal actor in Near-Eastern and Central Asian affairs. Without Turkey, the United States will achieve few of its regional objectives — whether in Iran, Afghanistan or the Arab world. The time has come to cut through the clichés surrounding it, treat Israel like a “normal” state and sever the umbilical cord.' ||
    '</p></section>' ||
    '<footer>' ||
    'Tony Judt (1948–2010) was the founder and director of the Remarque Institute at NYU and the author of <i>Postwar: A History of Europe Since 1945</i>, <i>Ill Fares the Land</i>, and <i>The Burden of Responsibility: Blum, Camus, Aron, and the French Twentieth Century</i>, among other books.' ||
    '</footer>',
    '2021-05-29'
),
(
    'thoughts-on-late-style',
    'Edward Said',
    'Thoughts on Late Style',
    '<header><p>Both in art and in our general ideas about the passage of human life there is assumed to be a general abiding timeliness</p></header>',
    '<section><p>' ||
    'We assume that the essential health of a human life has a great deal to do with its correspondence to its time – the fitting together of the two – and is therefore defined by its appropriateness or timeliness. Comedy, for instance, seeks its material in untimely behavior, an old man falling in love with a young woman (May in December), as in Molière and Chaucer, a philosopher acting like a child, a well person feigning illness. But it is also comedy as a form that brings about the restoration of timeliness through the komos with which such a work usually concludes – the marriage of young lovers. Yet, what of the last or late period of life, the decay of the body, the onset of ill health (which, in a younger person, brings on the possibility of an untimely end)? These issues, which interest me for obvious personal reasons, have led me to look at the way in which the work of some great artists and writers acquires a new idiom towards the end of their lives – what I’ve come to think of as a late style.' ||
    '</p><p>' ||
    'The accepted notion is that age confers a spirit of reconciliation and serenity on late works, often expressed in terms of a miraculous transfiguration of reality. In late plays such as The Tempest or The Winter’s Tale, Shakespeare returns to the forms of romance and parable; similarly, in Sophocles’ Oedipus at Colonus the aged hero is portrayed as having finally attained a remarkable holiness and sense of resolution. Or there is the well-known case of Verdi, who in his last years produced Otello and Falstaff, works that exude a renewed, almost youthful creativity and power.' ||
    '</p><p>' ||
    'Each of us can supply evidence of late works which crown a lifetime of aesthetic endeavor. Rembrandt and Matisse, Bach and Wagner. But what of artistic lateness not as harmony and resolution, but as intransigence, difficulty, and contradiction? What if age and ill health don’t produce serenity at all? This is the case with Ibsen, whose final works, especially When We Dead Awaken, tear apart his career and reopen questions that are supposed to have been resolved before such works are written. Far from resolution, Ibsen’s last plays suggest an angry and disturbed artist who uses drama as an occasion to stir up more anxiety, tamper irrevocably with the possibility of closure, leave the audience more perplexed and unsettled than before. It is this second type of lateness that I find deeply interesting: it is a sort of deliberately unproductive productiveness, a going against.' ||
    '</p><p>' ||
    'Adorno uses the phrase ‘late style’ most memorably in an essay fragment entitled ‘Spätstil Beethovens,’ dated 1937 and included in a 1964 collection, Moments musicaux, and again in his posthumously published book on Beethoven (1993). For Adorno, Beethoven’s last works – those that belong to what is known as the third period (the last five piano sonatas, the Ninth Symphony, the Missa Solemnis, the last six string quartets, 17 Bagatelles for the piano) – constitute an event in the history of modern culture: a moment when the artist who is fully in command of his medium nevertheless abandons communication with the established social order of which he is a part and achieves a contradictory, alienated relationship with it. His late works are a form of exile from his milieu.' ||
    '</p><p>' ||
    'So convincing as cultural symbol to Adorno was the figure of the ageing, deaf and isolated composer that it turns up in Thomas Mann’s Doctor Faustus – Adorno gave Mann a great deal of help with the novel – in the form of a lecture on Beethoven’s final period given by Adrian Leverkühn’s composition teacher, Wendell Kretschmar:' ||
    '</p><p>' ||
    'Beethoven’s art had overgrown itself, risen out of the habitable regions of tradition, even before the startled gaze of human eyes, into spheres of the entirely and utterly and nothing but personal – an ego painfully isolated in the absolute, isolated too from sense by the loss of his hearing; lonely prince of a realm of spirits, from whom now only a chilling breath issued to terrify his most willing contemporaries, standing as they did aghast at these communications of which only at moments, only by exception, they could understand anything at all.' ||
    '</p><p>' ||
    'There is heroism here, but also intransigence. Nothing about the essence of late Beethoven is reducible to the notion of art as a document: that is, to a reading of the music that stresses ‘reality is breaking through’ in the form of history or the composer’s sense of his impending death. If one thinks of them only as an expression of Beethoven’s personality, Adorno says, the ‘late works are relegated to the outer reaches of art, in the vicinity of the document. In fact, studies of the very late Beethoven seldom fail to refer to biography and fate. It is as if, confronted with the dignity of human death, the theory of art was to divest itself of its rights and abdicate in favor of reality.’ The late style is what happens if art does not abdicate its rights in favor of reality.' ||
    '</p><p>' ||
    'Impending death is a factor, of course, and cannot be denied. However, Adorno, who means to defend the rights of the aesthetic, is preoccupied with the formal law of Beethoven’s final compositional mode, a peculiar amalgam of subjectivity and convention, evident in such devices as ‘decorative trill sequences, cadences, and fiorituras.’ This law, he remarks, is revealed precisely in the thought of death . . . Death is imposed only on created beings, not on works of art, and thus it has appeared in art only in a That mode, as allegory . . . The power of subjectivity in the late works of art is the irascible gesture with which it takes leave of the works themselves. It breaks their bonds, not to express itself, but in order, expressionless, to cast off the appearance of art. Of the works themselves, it leaves only fragments behind, and communicates itself, like a cipher, only through the blank spaces from which it has disengaged itself. Touched by death, the hand of the master sets free the masses of material that he used to form; its tears and fissures, witnesses to the finite powerlessness of the confronted with the Being, are its final work.' ||
    '</p><p>' ||
    'It is the episodic character of Beethoven’s late work, its apparent carelessness about its continuity, that Adorno finds so gripping. When we compare such middle-period works as the Eroica with the Opus 110 sonata, say, we are struck by the cogent and integrative logic, the driven quality of the former and the somewhat distracted, often careless and repetitive character of the latter. Adorno speaks of the late work as ‘process, but not as development,’ as a ‘catching fire between the extremes, which no longer allow for any secure middle ground or harmony of spontaneity.’ Which is why, as Kretschmar says in Doctor Faustus, the late works often give the impression of being unfinished.' ||
    '</p><p>' ||
    'Adorno’s thesis is that all this is predicated on two considerations: first, that when he was young Beethoven’s work had been vigorous and organically whole, but became more wayward and eccentric; and second, that as an older man facing death, Beethoven realised that his work proclaims that ‘no synthesis is conceivable’: it is in effect ‘the remains of a synthesis, the vestige of an individual human subject sorely aware of the wholeness, and consequently the survival, that has eluded it ‘. Beethoven’s late works, therefore, communicate a tragic sense despite their irascibility. How exactly and poignantly Adorno discovers this is evident at the end of his essay. Noting that in Beethoven, as in Goethe, there is an ‘overabundance of material’, he goes on to say of Goethe’s late works – very much with an eye to Beethoven’s – that the ‘conventions’ are ‘splintered off’ from the main thrust of a piece, left to stand or fall away, abandoned. As for Beethoven’s great unisons, they are ranged beside huge polyphonic ensembles. ‘It is subjectivity,’ Adorno adds, that forcibly brings the extremes together at the moment, fills the dense polyphony with its tensions, breaks it apart with the unisono, and disengages itself, leaving the naked tone behind; that sets the mere phrase as a monument to what has been, marking a subjectivity turned to stone. The caesuras, the sudden discontinuities that more than anything else characterize the very late Beethoven, are those moments of breaking away; the work is silent at the instant when it is left behind, and turns its emptiness outward.' ||
    '</p><p>' ||
    'Adorno is describing the way that Beethoven seems to inhabit the late works as a lamenting personality, and then to leave the work or phrases in it incomplete, suddenly, abruptly jettisoned, as in the opening of the F major Quartet or the A minor – all this in marked contrast to the relentless quality of second-period works such as the Fifth Symphony, where the composer cannot seem to tear himself away from the piece. Adorno concludes that the style of the late works is both objectives, by its ‘fractured landscape,’ and subjective, by ‘the light in which – alone – it glows into life.’ Beethoven does not bring about a ‘harmonious synthesis,’ but ‘tears them apart in time, in order, perhaps, to preserve them for the eternal. In the history of art, late works are the catastrophe.’' ||
    '</p><p>' ||
    'The problem consists in trying to say what it is that holds the late works together, gives them unity, makes them more than just a collection of fragments. Here Adorno is at his most paradoxical: one cannot say what connects the parts other than by invoking ‘the figure they create together.’ Neither can one minimise the differences between the parts, and, it would appear, one cannot name the unity, or identify it in such a way as to reduce its catastrophic force. The power of Beethoven’s late style is negative, then. Indeed, it is negativity: in place of serenity and maturity, one finds a bristling, difficult and unyielding – perhaps inhuman – challenge. ‘The maturity of the late works,’ Adorno says, ‘does not resemble the kind one finds in fruit. They are . . . not round, but furrowed, even ravaged. Devoid of sweetness, bitter and spiny, they do not surrender themselves to mere delectation.’ Beethoven’s late works remain unco-opted by a higher synthesis: they do not fit any scheme, and they cannot be reconciled or resolved since their irresolution and fragmentariness are constitutive, neither ornamental nor symbolic of something else. The late works are about ‘lost totality,’ and it is in this sense that they are catastrophic.' ||
    '</p><p>' ||
    'But in what sense are they late? For Adorno, lateness has to do with surviving beyond what is acceptable and normal; he envisages nothing beyond lateness: it is impossible to transcend or surmount it; it can only be deepened. In The Philosophy of Music, he writes that Schoenberg essentially prolonged the irreconcilabilities, negations, and immobilities of the late Beethoven.' ||
    '</p><p>' ||
    'The reason Beethoven’s late style so fascinated Adorno is that it lies at the core of what is new in modern music of our own time. In Fidelio – the quintessential middle-period work – the idea of humanity is manifest throughout, and with it an idea of a better world. Late-style Beethoven keeps the Hegelian dialectic at a remove, and in so doing transforms music ‘more and more from something significant into something obscure – even to itself.’ It stands against the new bourgeois order and, as Adorno understood, forecasts the authentic and novel art of Schoenberg, whose ‘advanced music has no recourse but to insist on its ossification without concession to that would-be humanitarianism which it sees through.’ By then, he felt, music was ‘restricted to definitive negation.’ To that extent, Beethoven’s late style, remorselessly alienated and obscure, is the prototypical modern aesthetic form.' ||
    '</p><p>' ||
    'Lateness, then, and all that attends it in these astonishingly bold and bleak ruminations on the position of an aging artist, comes for Adorno to be the crucial aspect of aesthetics, and of his work as a critical theorist and philosopher. (My reading of Adorno, with his reflections about music very much at the center, sees him as injecting Marxism with a vaccine so powerful as to dissolve its agitational force almost completely. Not only do the notions of advance and culmination in Marxism crumble under his rigorous negative scorn, but so too does anything that suggests movement at all.) With old age and death before him, and promising start years behind, Adorno uses the model of late Beethoven to come to terms with an ending. However, this lateness is a thing in its right, not a premonition or obliteration of something else. Lateness is being at the end, fully conscious, full of memory, and also very (even preternaturally) aware of the present. Thus, like Beethoven, Adorno becomes a figure of lateness itself, an untimely and scandalous, even catastrophic commentator on the present.' ||
    '</p><p>' ||
    'There is an insistence in the late style not on mere aging, but on an increasing sense of apartness and exile and anachronism. It is precisely anachronism that characterizes the work of Adorno’s Italian contemporary Lampedusa, although Lampedusa’s single great work, The Leopard, is accessible to audiences who stay away from Adorno. Lampedusa is nonetheless a late-style practitioner whose interest for the modern reader is, I think, quite special.' ||
    '</p><p>' ||
    'This is the prerogative of late style: it has the power to render disenchantment and pleasure without resolving the contradiction between them. What holds them in tension, as equal forces straining in opposite directions, is the artist’s mature subjectivity, stripped of hubris and pomposity, unashamed either of its fallibility or of the modest assurance it has gained as a result of age and exile.' ||
    '</p></section>' ||
    '<footer>' ||
    'Edward Said (1935-2003) combined politics with scholarship, and showed how the two are intertwined. Deeply affected by the Arab-Israeli war, he became an inspiring guide to both history and culture, and his prose remains a joy to read. His books include <i>Orientalism</i> (1978), <i>Culture and Imperialism</i> (1993), <i>The Politics of Dispossession</i> (1995), <i>Peace and its Discontents</i> (1996), and <i>The End of the Peace Process</i> (2000).' ||
    '</footer>',
    '2021-06-01'
),
(
    'double-standards',
    'Edward Said',
    'Double standards',
    '<header><p>The US celebrates Serb freedom, but the case of the Palestinians is, apparently, different</p></header>',
    '<section><p>' ||
    'Misreported and hopelessly flawed from the start, the Oslo peace process has entered its terminal phase - of violent confrontation, disproportionately massive Israeli repression, widespread Palestinian rebellion and great loss of life, the vast majority of it Palestinian. Ariel Sharon''s visit to Haram al-Sharif on September 28 could not have occurred without Ehud Barak''s concurrence. How else could the paunchy old war criminal have appeared there with a thousand soldiers guarding him? Barak''s approval rating rose from 20% to 50% after the visit, and the stage seems set for a national unity government ready to be still more violent and repressive.' ||
    '</p><p>' ||
    'The portents of this disarray, however, were there from the 1993 start. Labour and Likud leaders alike made no secret of the fact that Oslo was designed to segregate the Palestinians in non-contiguous enclaves, surrounded by Israeli-controlled borders, with settlements and settlement roads punctuating and essentially violating the territories'' integrity, expropriations and house demolitions proceeding inexorably through the Rabin, Peres, Netanyahu and Barak administrations along with the expansion and multiplication of settlements (200,000 Israeli Jews added to Jerusalem, 200,000 more in Gaza and the West Bank), military occupation continuing and every tiny step taken toward Palestinian sovereignty - including agreements to withdraw in minuscule, agreed-upon phases - stymied, delayed, cancelled at Israel''s will.' ||
    '</p><p>' ||
    'This method was politically and strategically absurd, even suicidal. Occupied East Jerusalem was placed out of bounds by a bellicose Israeli campaign to decree the intractably divided city off limits to Palestinians and to claim it as Israel''s "eternal, undivided capital". The 4m Palestinian refugees - now the largest and longest existing such population anywhere - were told that they could forget about any idea of return or compensation.' ||
    '</p><p>' ||
    'With his own corrupt and stupidly repressive regime supported both by Israel''s Mossad and the CIA, Yasser Arafat continued to rely on US mediation, even though the US peace team was dominated by former Israeli lobby officials and a president whose ideas about the Middle East were those of a Christian fundamentalist Zionist with no exposure to or understanding of the Arab-Islamic world. Compliant, but isolated and unpopular Arab chiefs (especially Egypt''s President Mubarak) were compelled humiliatingly to toe the American line, thereby further diminishing their eroded credibility at home. Israel''s priorities were always put first, as was its bottomless insecurity and its preposterous demands. No attempt was made to address the fundamental injustice done when Palestinians as a people were dispossessed in 1948.' ||
    '</p><p>' ||
    'Behind the peace process were two unchanging Israeli/American presuppositions, both of them derived from a startling incomprehension of reality. First was that given enough punishment and beating over the years since 1948, Palestinians would ultimately give up, accept the compromised compromises Arafat did in fact accept, and call the whole Palestinian cause off, thereafter excusing Israel for everything it has done. Thus, for example, the "peace process" gave no considered attention to immense Palestinian losses of land and goods, none to the links between past dislocation and present statelessness, while as a nuclear power with a formidable military, Israel nevertheless continued to claim the status of victim and demand restitution for genocidal anti-semitism in Europe. Incongruously, there has still been no official acknowledgement of Israel''s (by now amply documented) responsibility for the tragedy of 1948, even as the US went to war in Iraq and Kosovo on behalf of other refugees. But one can''t force people to forget, especially when the daily reality was seen by all Arabs as endlessly reproducing the original injustice.' ||
    '</p><p>' ||
    'Second, after seven years of steadily worsening economic and social conditions for Palestinians everywhere, Israeli and US policymakers persisted (stupidly, I think) in trumpeting their successes, excluding the UN and other interested parties, bending the disgracefully partisan media to their wills, distorting the actuality into ephemeral victories for "peace". With the entire Arab world up in arms over Israeli helicopter gunships and heavy artillery demolishing Palestinian civilian buildings, with almost 100 fatalities and almost 2,000 wounded (including many children) and with Palestinian Israelis up in arms against their treatment as third-class, non-Jewish citizens, the misaligned and skewed status quo is falling apart. Isolated in the UN and unloved everywhere in the Arab world as Israel''s unconditional champion, the US and its lame duck president have little to contribute any more.' ||
    '</p><p>' ||
    'Neither does the Arab and Israeli leadership, even though they are likely to cobble together another interim agreement. Most shocking has been the total silence of the Zionist peace camp in the US, Europe and Israel. The slaughter of Palestinian youths goes on and this band of supposed peace-lovers either backs Israeli brutality or expresses disappointment at Palestinian ingratitude. Worst of all is the US media, completely cowed by the fearsome Israeli lobby, with commentators and anchors spinning distorted reports about "crossfire" and "Palestinian violence" that eliminate the fact that Israel is in military occupation and that Palestinians are fighting it, not "laying siege to Israel", as the ghastly Mrs Albright put it. While the US celebrates the Serbian people''s victory over Slobodan Milosevic, Clinton and his minions refuse to see the Palestinian insurgency as the same kind of struggle against injustice.' ||
    '</p><p>' ||
    'My guess is that some of the new Palestinian intifada is directed at Arafat, who has led his people astray with phony promises, and maintained a battery of corrupt officials holding down commercial monopolies even as they negotiate incompetently and weakly on his behalf. Some 60% of the public budget is disbursed by Arafat to bureaucracy and security, only 2% to the infrastructure. Three years ago his own accountants admitted to an annual $400m in disappeared funds. His international patrons accept this in the name of the "peace process", certainly the most hated phrase in the Palestinian lexicon today.' ||
    '</p><p>' ||
    'An alternative peace plan and leadership is slowly emerging among Israeli, West Bank, Gaza and diaspora Palestinians. No return to the Oslo framework; no compromise on the original UN resolutions (242, 338, and 194) "mandating the Madrid conference in 1991; removal of all settlements and military roads; evacuation of all the territories annexed or occupied in 1967; boycott of Israeli goods and services. A new sense may actually be dawning that only a mass movement against Israeli apartheid (similar to the South African variety) will work. Certainly it is sheer idiocy for Barak and Albright to hold Arafat responsible for what he no longer fully controls. Rather than dismissing the new framework being proposed, Israel''s supporters would be wise to remember that the question of Palestine concerns an entire people, not an ageing and discredited leader. Besides, peace in Palestine/Israel can only be made between equals once the military occupation has ended. No Palestinian, not even Arafat, can really accept anything less.' ||
    '</p></section>' ||
    '<footer>' ||
    'Edward Said (1935-2003) combined politics with scholarship, and showed how the two are intertwined. Deeply affected by the Arab-Israeli war, he became an inspiring guide to both history and culture, and his prose remains a joy to read. His books include <i>Orientalism</i> (1978), <i>Culture and Imperialism</i> (1993), <i>The Politics of Dispossession</i> (1995), <i>Peace and its Discontents</i> (1996), and <i>The End of the Peace Process</i> (2000).' ||
    '</footer>',
    '2021-06-02'
),
(
    'reality-of-drone-warfare',
    'Derek Gregory',
    'How a Hollywood film reveals the reality of drone warfare',
    '<header><p>As Helen Mirren’s new film Eye in the Sky is released, an expert reflects on the morality of how and when to use drones in war</p></header>',
    '<section><p>' ||
    'Gavin Hood’s film <i>Eye in the Sky</i> is a thrillingly intelligent exploration of the political and ethical questions surrounding drone warfare. It has been carefully researched and is on the cutting edge of what is currently possible. (Full disclosure: I offered the screenwriter early advice.) But there’s a longer history and a wider geography that casts those issues in a different light.' ||
    '</p><p>' ||
    'As soon as the Wright brothers demonstrated the possibility of human flight, others were busy imagining flying machines with nobody on board. In 1910 the engineer Raymond Phillips captivated crowds in the London Hippodrome with a remotely controlled airship that floated out over the stalls and, when he pressed a switch, released hundreds of paper birds on to the heads of the audience below. When he built the real thing, he promised, the birds would be replaced with bombs. Sitting safely in London he could attack Paris or Berlin.' ||
    '</p><p>' ||
    'There has always been something hideously theatrical about bombing – recall the shock and awe visited on the inhabitants of Baghdad in 2003. The spectacle now includes the marionette movements of drones, Predators and Reapers whose electronic strings are pulled from thousands of miles away.' ||
    '</p><p>' ||
    'Remoteness, however, is an elastic measure. Human beings have been killing others at ever greater distances since the invention of the dart, the spear and the slingshot. The invention of firearms wrought another transformation in the range of military violence. And yet today, in a world shrunk by the very technologies that have made the deployment of armed drones possible, the use of these remote platforms seems to turn distance back into a moral absolute.' ||
    '</p><p>' ||
    'But if it is wrong to kill someone from 7,500 miles away (the distance from Creech air force base in Nevada to Afghanistan), over what distance is it permissible to kill somebody? For some, the difference is that drone crews are safe in the continental United States – their lives are not on the line – and this has become a constant refrain in the drone debates. In fact, the US Air Force has been concerned about the safety of its aircrews ever since its high losses during the second world war. After Hiroshima and Nagasaki, it experimented with remotely controlled B-17 and B-47 aircraft to drop nuclear bombs without exposing aircrews to danger from the blast, and today it lauds its Predators and Reapers for their ability to “project power without vulnerability”.' ||
    '</p><p>' ||
    'It’s a complicated boast, because these remote platforms are slow, sluggish and easy to shoot down. They can only be used in uncontested air space against people who can’t fight back. There are almost 200 people involved in every combat air patrol and most of them are indeed out of harm’s way. But in Afghanistan the launch and recovery and the maintenance crews – Predators and Reapers have a short range, so that they have to be launched by crews close to their targets – are exposed to real danger.' ||
    '</p><p>' ||
    'Bombing in the major wars of the 20th century was always dangerous to those who carried it out, but those who dropped bombs over Hamburg or Cologne in the second world war or Vietnam in the 1960s and 1970s were, in a crucial sense, also remote from their targets. “The good thing about being in an aeroplane at war is that you never touch the enemy”, recalled one veteran of Bomber Command. “You never see the whites of their eyes.”' ||
    '</p><p>' ||
    'Distance no longer confers blindness on those who operate today’s drones. They have a much closer, more detailed view of the people they kill. The US Air Force describes their job as putting “warheads on foreheads”, and they are required to remain on station to carry out a battle damage assessment that is often an inventory of body parts.  Most drone crews will tell you that they do not feel thousands of miles away from the action: just 18 inches, the distance from eye to screen.' ||
    '</p><p>' ||
    'Their primary function is to provide intelligence, surveillance and reconnaissance. Although drones have been armed since 2001, until 2012 they were directly responsible for only 5 to 10% of air strikes in Afghanistan. But they were involved in orchestrating more.' ||
    '</p><p>' ||
    'Flying a Predator or a Reaper “is more like being a manager”, one pilot has explained. “You’re managing multiple assets and you’re involved with the other platforms using the information coming off of your aircraft.”' ||
    '</p><p>' ||
    'In principle it’s not so different from using aircraft to range targets for artillery on the Western Front, but the process has been radicalised by the drone’s real-time full-motion video feeds that enable highly mobile “targets of opportunity” to be identified and tracked. In the absence of ground intelligence, this becomes crucial: until drones were relocated in sufficient numbers from Afghanistan and elsewhere to enable purported IS-targets in Syria to be identified, most US aircraft were returning to base without releasing their weapons.' ||
    '</p><p>' ||
    'Armed drones are used to carry out targeted killings, both inside and outside areas of “active hostilities”, and to provide close air support to ground troops. Targeted killing has spurred an intense critical debate, and rightly so – this is the focus of Eye in the Sky too – but close air support has not been subject to the same scrutiny. In both cases, video feeds are central, but it is a mistake to think that this reduces war to a video game – a jibe that in any case fails to appreciate that today’s video games are often profoundly immersive.' ||
    '</p><p>' ||
    'In fact, that may be part of the problem. Several studies have shown that civilian casualties are most likely when air strikes are carried out to support troops in contact with an enemy, and even more likely when they are carried out from remote platforms. I suspect that drone crews may compensate for their physical rather than emotional distance by “leaning forward” to do everything they can to protect the troops on the ground.' ||
    '</p><p>' ||
    'This in turn predisposes them to interpret every action in the vicinity of a ground force as hostile – and civilians as combatants – not least because these are silent movies: the only sound, apart from the clacking of computer keys as they talk in secure chatrooms with those watching the video feeds, comes from radio communications with their own forces.' ||
    '</p><p>' ||
    'In contrast to those shown in Eye in the Sky, those feeds are often blurry, fuzzy, indistinct, broken, compressed – and, above all, ambiguous. How can you be sure that is an insurgent burying an IED and not a farmer digging a ditch? The situation is more fraught because the image stream is watched by so many other eyes on the ground, who all have their own ideas about what is being shown and what to do about it.' ||
    '</p><p>' ||
    'Combining sensor and shooter in the same (remote) platform may have “compressed the kill-chain”, as the air force puts it, and this is vital in an era of “just in time”, liquid war where everything happens so fast.' ||
    '</p><p>' ||
    'Yet in another sense the kill-chain has been spectacularly extended: senior officers, ground force commanders, military lawyers and video analysts all have access to the feeds. There’s a wonderful passage in Brian Castner’s book All the Ways we Kill and Die that captures the dilemma perfectly.' ||
    '</p><p>' ||
    '“A human in the loop?” Castner’s drone pilot complains. “Try two or three or 100 humans in the loop. Gene was the eye of the needle, and the whole war and a thousand rich generals must pass through him ... If they wanted to fly the fucking plane, they could come out and do it themselves.”' ||
    '</p><p>' ||
    'This is the networked warfare, scattered over multiple locations around the world, shown in Eye in the Sky. But the network often goes down and gets overloaded – it’s not a smooth and seamlessly functioning machine – and it is shot through with ambiguity, uncertainty and indecision.' ||
    '</p><p>' ||
    'And often those eyes in the sky multiply, rather than disperse, the fogs of war.' ||
    '</p></section>' ||
    '<footer>' ||
    'Derek Gregory is the Peter Wall Distinguished Professor at the University of British Columbia. His books include <i>Geographical Imaginations</i>, <i>The Colonial Present</i>, and <i>Violent Geographies: Fear, Terror and Political Violence</i>.' ||
    '</footer>',
    '2021-06-03'
),
(
    'cuban-missile-crisis',
    'Noam Chomsky',
    'Cuban missile crisis: how the US played Russian roulette with nuclear war',
    '<header><p>President Kennedy is often lauded for managing the crisis. The reality is he took stunning risks to impose American hegemony</p></header>',
    '<section><p>' ||
    'The world stood still 50 years ago during the last week of October, from the moment when it learned that the Soviet Union had placed nuclear-armed missiles in Cuba until the crisis was officially ended – though, unknown to the public, only officially.' ||
    '</p><p>' ||
    'The image of the world standing still is due to Sheldon Stern, former historian at the John F Kennedy Presidential Library, who published the authoritative version of the tapes of the ExComm meetings where Kennedy, and a close circle of advisers, debated how to respond to the crisis. The meetings were secretly recorded by the president, which might bear on the fact that his stand throughout the recorded sessions is relatively temperate, as compared to other participants who were unaware that they were speaking to history. Stern has just published an accessible and accurate review of this critically important documentary record, finally declassified in the 1990s. I will keep to that here. "Never before or since," he concludes, "has the survival of human civilization been at stake in a few short weeks of dangerous deliberations," culminating in the Week the World Stood Still.' ||
    '</p><p>' ||
    'There was good reason for the global concern. A nuclear war was all too imminent – a war that might "destroy the Northern Hemisphere", President Eisenhower had warned. Kennedy''s own judgment was that the probability of war might have been as high as 50%. Estimates became higher as the confrontation reached its peak and the "secret doomsday plan to ensure the survival of the government was put into effect" in Washington, described by journalist Michael Dobbs in his recent, well-researched bestseller on the crisis – though he doesn''t explain why there would be much point in doing so, given the likely nature of nuclear war. Dobbs quotes Dino Brugioni, "a key member of the CIA team monitoring the Soviet missile build-up", who saw no way out except "war and complete destruction" as the clock moved to One Minute to Midnight – Dobbs'' title. Kennedy''s close associate, historian Arthur Schlesinger, described the events as "the most dangerous moment in human history". Defense Secretary Robert McNamara wondered aloud whether he "would live to see another Saturday night", and later recognized that "we lucked out" – barely.' ||
    '</p><p>' ||
    'A closer look at what took place adds grim overtones to these judgments, with reverberations to the present moment.' ||
    '</p><p>' ||
    'There are several candidates for "the most dangerous moment". One is 27 October, when US destroyers enforcing the quarantine around Cuba were dropping depth-charges on Soviet submarines. According to Soviet accounts, reported by the National Security Archive, submarine commanders were "rattled enough to talk about firing nuclear torpedoes, whose 15 kiloton explosive yields approximated the bomb that devastated Hiroshima in August 1945".' ||
    '</p><p>' ||
    'In one case, a reported decision to assemble a nuclear torpedo for battle readiness was aborted at the last minute by Second Captain Vasili Archipov, who may have saved the world from nuclear disaster. There is little doubt what the US reaction would have been had the torpedo been fired, or how the Russians would have responded as their country was going up in smoke. Kennedy had already declared the highest nuclear alert short of launch (Defcon 2), which authorized "Nato aircraft with Turkish pilots ... [or others] ... to take off, fly to Moscow, and drop a bomb", according to Harvard University strategic analyst Graham Allison, in Foreign Affairs.' ||
    '</p><p>' ||
    'Another candidate is the previous day, 26 October. That day is selected as "the most dangerous moment" by a B-52 pilot, Major Don Clawson, who piloted one of those Nato aircrafts and provides a hair-raising description of details of the Chrome Dome (CD) missions during the crisis, "B-52s on airborne alert" with nuclear weapons "on board and ready to use". 26 October was the day when "the nation was closest to nuclear war," Clawson writes in his "irreverent anecdotes of an Air Force pilot", Is That Something the Crew Should Know? On that day, Clawson himself was in a good position to set off a likely terminal cataclysm. He concludes that:' ||
    '</p><p>' ||
    '<i>"We were damned lucky we didn''t blow up the world – and no thanks to the political or military leadership of this country."</i>' ||
    '</p><p>' ||
    'The errors, confusions, near-accidents and miscomprehension of the leadership that Clawson reports are startling enough, but not as much as the operative command-and-control rules – or lack of them. As Clawson recounts his experiences during the 15, 24-hour CD missions he flew – the maximum possible – the official commanders "did not possess the capability to prevent a rogue crew or crew-member from arming and releasing their thermonuclear weapons", or even from broadcasting a mission that would have sent off "the entire airborne alert force without possibility of recall". Once the crew was airborne, carrying thermonuclear weapons, he writes:' ||
    '</p><p>' ||
    '<i>"It would have been possible to arm and drop them all with no further input from the ground. There was no inhibitor on any of the systems."</i>' ||
    '</p><p>' ||
    'About one-third of the total force was in the air, according to General David Burchinal, director of plans on the air staff at Air Force headquarters. The Strategic Air Command, technically in charge, appears to have had little control. And according to Clawson''s account, the civilian National Command Authority was kept in the dark by SAC, which means that the ExComm "deciders" pondering the fate of the world knew even less. General Burchinal''s oral history is no less hair-raising, and reveals even greater contempt for the civilian command. According to him, Russian capitulation was never in doubt. The CD operations were designed to make it crystal clear to the Russians that they were hardly even competing in the military confrontation, and could quickly have been destroyed.' ||
    '</p><p>' ||
    'From the ExComm records, Stern concludes that on 26 October President Kennedy was "leaning towards military action to eliminate the missiles" in Cuba, to be followed by invasion, according to Pentagon plans. It was evident then that the act might have led to terminal war, a conclusion fortified much later by revelations that tactical nuclear weapons had been deployed, and that Russian forces were far greater than US intelligence had reported.' ||
    '</p><p>' ||
    'As the ExComm meetings were drawing to a close at 6pm on the 26 October, a letter arrived from Prime Minister Khrushchev, directly to President Kennedy. Khrushchev''s "message seemed clear," Stern writes:' ||
    '</p><p>' ||
    '<i>"The missiles would be removed if the US promised not to invade Cuba."</i>' ||
    '</p><p>' ||
    'The next day, at 10am, the president again turned on the secret tape. He read aloud a wire service report that had just been handed to him:' ||
    '</p><p>' ||
    '<i>"Premier Khrushchev told President Kennedy in a message today he would withdraw offensive weapons from Cuba if the United States withdrew its rockets from Turkey."</i>' ||
    '</p><p>' ||
    'These were Jupiter missiles with nuclear warheads. The report was soon authenticated. Though received by the committee as an unexpected bolt from the blue, it had actually been anticipated: "We''ve known this might be coming for a week," Kennedy informed them. To refuse public acquiescence would be difficult, he realized. These were obsolete missiles, already slated for withdrawal, to be replaced by far more lethal and effectively invulnerable Polaris submarines. Kennedy recognized that he would be in an "insupportable position if this becomes [Khrushchev''s] proposal", both because the Turkish missiles were useless and were being withdrawn anyway, and because "it''s gonna – to any man at the United Nations or any other rational man, it will look like a very fair trade."' ||
    '</p><p>' ||
    'The planners therefore faced a serious dilemma: they had in hand two somewhat different proposals from Khrushchev to end the threat of catastrophic war, and each would seem to any "rational man" to be a fair trade. How then to react?' ||
    '</p><p>' ||
    'One possibility would have been to breathe a sigh of relief that civilization could survive, to eagerly accept both offers and to announce that the US would adhere to international law and remove any threat to invade Cuba; and to carry forward the withdrawal of the obsolete missiles in Turkey, proceeding as planned to upgrade the nuclear threat against the Soviet Union to a far greater one, of course, only part of the global encirclement of Russia. But that was unthinkable.' ||
    '</p><p>' ||
    'The basic reason why no such thought could be contemplated was spelled out by National Security Adviser McGeorge Bundy, former Harvard Dean and reputedly the brightest star in the Camelot firmament. The world must come to understand that "the current threat to peace is not in Turkey, it is in Cuba," where missiles are directed against us. A vastly more powerful US missile force trained on the much weaker and more vulnerable Soviet enemy cannot possibly be regarded as a threat to peace, because we are Good, as a great many people in the western hemisphere and beyond could testify – among numerous others, the victims of the ongoing terrorist war that the US was then waging against Cuba, or those swept up in the "campaign of hatred" in the Arab world that so puzzled Eisenhower (though not the National Security Council, which explained it clearly).' ||
    '</p><p>' ||
    'And, of course, the idea that the US should be restrained by international law was too ridiculous to merit consideration. As explained recently by the respected liberal commentator Matthew Yglesias, "one of the main functions of the international institutional order is precisely to legitimate the use of deadly military force by western powers" – meaning the US – so that it is "amazingly naïve", indeed quite "silly", to suggest that the US should obey international law or other conditions that we impose on the powerless: a frank and welcome exposition of operative assumptions, reflexively taken for granted by the ExComm assemblage.' ||
    '</p><p>' ||
    'In subsequent colloquy, the president stressed that we would be "in a bad position" if we chose to set off an international conflagration by rejecting proposals that would seem quite reasonable to survivors, if any cared. This "pragmatic" stance was about as far as moral considerations could reach. In a review of recently-released documents on Kennedy-era terror, Harvard University Latin Americanist Jorge Domínguez observes that:' ||
    '</p><p>' ||
    '<i>"Only once in these nearly thousand pages of documentation did a US official raise something that resembled a faint moral objection to US government-sponsored terrorism."</i>' ||
    '</p><p>' ||
    'A member of the National Security Council staff suggested that raids that are "haphazard and kill innocents … might mean a bad press in some friendly countries." The same attitudes prevail throughout the internal discussions during the missile crisis, as when Robert Kennedy warned that a full-scale invasion of Cuba would "kill an awful lot of people, and we''re going to take an awful lot of heat on it." And they prevail to the present with only the rarest of exceptions, as easily documented.' ||
    '</p><p>' ||
    'We might have been "in even a worse position" if the world had known more about what the US was doing at the time. It was only recently learned that, six months earlier, the US had secretly deployed in Okinawa missiles virtually identical to those the Russians later sent to Cuba. These were surely aimed at China, at a moment of elevated regional tensions. Okinawa remains a major offensive US military base, over the bitter objections of its inhabitants – who, right now, are less than enthusiastic about the dispatch of accident-prone V-22 Osprey helicopters to the Fukenma military base, located at the heart of a heavily-populated urban center.' ||
    '</p><p>' ||
    'In the deliberations that followed, the US pledged to withdraw the obsolete missiles from Turkey, but would not do so publicly or in writing: it was important that Khrushchev be seen to capitulate. An interesting reason was offered, and is accepted as reasonable by scholarship and commentary. As Dobbs puts it:' ||
    '</p><p>' ||
    '<i>"If it appeared that the United States was dismantling the missile bases unilaterally, under pressure from the Soviet Union, the [Nato] alliance might crack."</i>' ||
    '</p><p>' ||
    'Or, to rephrase a little more accurately, if the US replaced useless missiles with a far more lethal threat, as already planned, in a trade with Russia that any "rational man" would regard as very fair, then the Nato alliance might crack. To be sure, when Russia withdrew Cuba''s only deterrent against ongoing US attack with a severe threat to proceed to direct invasion and quietly departed from the scene, the Cubans would be infuriated – as they were, understandably. But that is an unfair comparison for the standard reasons: we are human beings who matter, while they are merely "unpeople", to borrow Orwell''s useful phrase.' ||
    '</p><p>' ||
    'Kennedy also made an informal pledge not to invade Cuba, but with conditions: not just withdrawal of the missiles, but also termination, or at least "a great lessening", of any Russian military presence. (Unlike Turkey, on Russia''s borders, where nothing of the kind could be contemplated.) When Cuba is no longer an "armed camp", then "we probably wouldn''t invade," in the president''s words. He added also that if it hoped to be free from the threat of US invasion, Cuba must end its "political subversion" (Stern''s phrase) in Latin America.' ||
    '</p><p>' ||
    'Political subversion had been a constant theme for years, invoked, for example, when Eisenhower overthrew the parliamentary government of Guatemala and plunged the tortured country into an abyss from which it has yet to emerge. And the themes remained alive and well right through Reagan''s vicious terror wars in Central America in the 1980s. The "political subversion" consisted of support for those resisting the murderous assaults of the US and its client regimes, and sometimes – horror of horrors – perhaps even providing arms to the victims.' ||
    '</p></section>' ||
    '<footer>' ||
    'Noam Chomsky is an American linguist, philosopher, cognitive scientist, historian, social critic, and political activist. Sometimes called "the father of modern linguistics", Chomsky is also a major figure in analytic philosophy and one of the founders of the field of cognitive science.' ||
    '</footer>',
    '2021-06-04'
),
(
    'who-rules-the-world',
    'Noam Chomsky',
    'Who rules the world? America is no longer the obvious answer',
    '<header><p>Challenged from all sides, the US is losing its tight grip on international power, as world public opinion becomes a ‘second superpower’',
    '<section><p>' ||
    'When we ask “who rules the world?” we commonly adopt the standard convention that the actors in world affairs are states, primarily the great powers, and we consider their decisions and the relations among them. That is not wrong. But we would do well to keep in mind that this level of abstraction can also be highly misleading.' ||
    '</p><p>' ||
    'States, of course, have complex internal structures, and the choices and decisions of the political leadership are heavily influenced by internal concentrations of power, while the general population is often marginalized. That is true even for the more democratic societies, and obviously for others. We cannot gain a realistic understanding of who rules the world while ignoring the “masters of mankind”, as Adam Smith called them: in his day, the merchants and manufacturers of England; in ours, multinational conglomerates, huge financial institutions, retail empires and the like.' ||
    '</p><p>' ||
    'Still following Smith, it is also wise to attend to the “vile maxim” to which the “masters of mankind” are dedicated: “All for ourselves and nothing for other people” – a doctrine known otherwise as bitter and incessant class war, often one-sided, much to the detriment of the people of the home country and the world.' ||
    '</p><p>' ||
    'In the contemporary global order, the institutions of the masters hold enormous power, not only in the international arena but also within their home states, on which they rely to protect their power and to provide economic support by a wide variety of means.' ||
    '</p><p>' ||
    'When we consider the role of the masters of mankind, we turn to such state policy priorities of the moment as the Trans-Pacific Partnership, one of the investor-rights agreements mislabeled “free-trade agreements” in propaganda and commentary. They are negotiated in secret, apart from the hundreds of corporate lawyers and lobbyists writing the crucial details. The intention is to have them adopted in good Stalinist style with “fast track” procedures designed to block discussion and allow only the choice of yes or no (hence yes).' ||
    '</p><p>' ||
    'The designers regularly do quite well, not surprisingly. People are incidental, with the consequences one might anticipate.' ||
    '</p><p>' ||
    'The neoliberal programs of the past generation have concentrated wealth and power in far fewer hands while undermining functioning democracy, but they have aroused opposition as well, most prominently in Latin America but also in the centers of global power.' ||
    '</p><p>' ||
    'The European Union (EU), one of the more promising developments of the post-world war II period, has been tottering because of the harsh effect of the policies of austerity during recession, condemned even by the economists of the International Monetary Fund (if not the IMF’s political actors).' ||
    '</p><p>' ||
    'Democracy has been undermined as decision-making shifted to the Brussels bureaucracy, with the northern banks casting their shadow over their proceedings.' ||
    '</p><p>' ||
    'Mainstream parties have been rapidly losing members to left and to right. The executive director of the Paris-based research group EuropaNova attributes the general disenchantment to “a mood of angry impotence as the real power to shape events largely shifted from national political leaders [who, in principle at least, are subject to democratic politics] to the market, the institutions of the European Union and corporations”, quite in accord with neoliberal doctrine.' ||
    '</p><p>' ||
    'Very similar processes are under way in the United States, for somewhat similar reasons, a matter of significance and concern not just for the country but, because of US power, for the world.' ||
    '</p><p>' ||
    'The rising opposition to the neoliberal assault highlights another crucial aspect of the standard convention: it sets aside the public, which often fails to accept the approved role of “spectators” (rather than “participants”) assigned to it in liberal democratic theory. Such disobedience has always been of concern to the dominant classes. Just keeping to American history, George Washington regarded the common people who formed the militias that he was to command as “an exceedingly dirty and nasty people [evincing] an unaccountable kind of stupidity in the lower class of these people”.' ||
    '</p><p>' ||
    'In Violent Politics, his masterful review of insurgencies from “the American insurgency” to contemporary Afghanistan and Iraq, William Polk concludes that General Washington “was so anxious to sideline [the fighters he despised] that he came close to losing the Revolution”. Indeed, he “might have actually done so” had France not massively intervened and “saved the Revolution”, which until then had been won by guerrillas – whom we would now call “terrorists” – while Washington’s British-style army “was defeated time after time and almost lost the war”.' ||
    '</p><p>' ||
    'A common feature of successful insurgencies, Polk records, is that once popular support dissolves after victory, the leadership suppresses the “dirty and nasty people” who actually won the war with guerrilla tactics and terror, for fear that they might challenge class privilege. The elites’ contempt for “the lower class of these people” has taken various forms throughout the years.' ||
    '</p><p>' ||
    'In recent times one expression of this contempt is the call for passivity and obedience (“moderation in democracy”) by liberal internationalists reacting to the dangerous democratizing effects of the popular movements of the 1960s.' ||
    '</p><p>' ||
    'Sometimes states do choose to follow public opinion, eliciting much fury in centers of power. One dramatic case was in 2003, when the Bush administration called on Turkey to join its invasion of Iraq.' ||
    '</p><p>' ||
    'Ninety-five percent of Turks opposed that course of action and, to the amazement and horror of Washington, the Turkish government adhered to their views. Turkey was bitterly condemned for this departure from responsible behavior. Deputy Secretary of Defense Paul Wolfowitz, designated by the press as the “idealist-in-chief” of the administration, berated the Turkish military for permitting the malfeasance of the government and demanded an apology. Unperturbed by these and innumerable other illustrations of our fabled “yearning for democracy”, respectable commentary continued to laud President George W Bush for his dedication to “democracy promotion”, or sometimes criticized him for his naivete in thinking that an outside power could impose its democratic yearnings on others.' ||
    '</p><p>' ||
    'The Turkish public was not alone. Global opposition to US-UK aggression was overwhelming. Support for Washington’s war plans scarcely reached 10% almost anywhere, according to international polls. Opposition sparked huge worldwide protests, in the United States as well, probably the first time in history that imperial aggression was strongly protested even before it was officially launched.' ||
    '</p><p>' ||
    'On the front page of the New York Times, journalist Patrick Tyler reported that “there may still be two superpowers on the planet: the United States and world public opinion”.' ||
    '</p><p>' ||
    'Unprecedented protest in the US was a manifestation of the opposition to aggression that began decades earlier in the condemnation of the US wars in Indochina, reaching a scale that was substantial and influential, even if far too late.' ||
    '</p><p>' ||
    'By 1967, when the antiwar movement was becoming a significant force, military historian and Vietnam specialist Bernard Fall warned that “Vietnam as a cultural and historic entity … is threatened with extinction … [as] the countryside literally dies under the blows of the largest military machine ever unleashed on an area of this size”.' ||
    '</p><p>' ||
    'But the antiwar movement did become a force that could not be ignored. Nor could it be ignored when Ronald Reagan came into office determined to launch an assault on Central America. His administration mimicked closely the steps John F Kennedy had taken 20 years earlier in launching the war against South Vietnam, but had to back off because of the kind of vigorous public protest that had been lacking in the early 1960s.' ||
    '</p><p>' ||
    'The assault was awful enough. The victims have yet to recover. But what happened to South Vietnam and later all of Indochina, where “the second superpower” imposed its impediments only much later in the conflict, was incomparably worse.' ||
    '</p><p>' ||
    'It is often argued that the enormous public opposition to the invasion of Iraq had no effect. That seems incorrect to me.' ||
    '</p><p>' ||
    'Again, the invasion was horrifying enough, and its aftermath is utterly grotesque. Nevertheless, it could have been far worse.' ||
    '</p><p>' ||
    'Vice-President Dick Cheney, secretary of defense Donald Rumsfeld, and the rest of Bush’s top officials could never even contemplate the sort of measures that President Kennedy and President Lyndon Johnson adopted 40 years earlier largely without protest.' ||
    '</p><p>' ||
    '<i><b>The challenges today: the Islamic world</b></i>' ||
    '</p><p>' ||
    'Let us turn to the third region of major concern, the (largely) Islamic world, also the scene of the global war on terror (GWOT) that George W Bush declared in 2001 after the 9/11 terrorist attack. To be more accurate, re-declared.' ||
    '</p><p>' ||
    'The GWOT was declared by the Reagan administration when it took office, with fevered rhetoric about a “plague spread by depraved opponents of civilization itself” (as Reagan put it) and a “return to barbarism in the modern age” (the words of George Shultz, his secretary of state).' ||
    '</p><p>' ||
    'The original GWOT has been quietly removed from history. It very quickly turned into a murderous and destructive terrorist war afflicting Central America, southern Africa, and the Middle East, with grim repercussions to the present, even leading to condemnation of the United States by the World Court (which Washington dismissed). In any event, it is not the right story for history, so it is gone.' ||
    '</p><p>' ||
    'The success of the Bush-Obama version of GWOT can readily be evaluated on direct inspection. When the war was declared, the terrorist targets were confined to a small corner of tribal Afghanistan. They were protected by Afghans, who mostly disliked or despised them, under the tribal code of hospitality – which baffled Americans when poor peasants refused “to turn over Osama bin Laden for the, to them, astronomical sum of $25m”.' ||
    '</p><p>' ||
    'There are good reasons to believe that a well-constructed police action, or even serious diplomatic negotiations with the Taliban, might have placed those suspected of the 9/11 crimes in American hands for trial and sentencing. But such options were off the table. Instead, the reflexive choice was large-scale violence – not with the goal of overthrowing the Taliban (that came later) but to make clear US contempt for tentative Taliban offers of the possible extradition of bin Laden.' ||
    '</p><p>' ||
    'How serious these offers were we do not know, since the possibility of exploring them was never entertained. Or perhaps the US was just intent on “trying to show its muscle, score a victory and scare everyone in the world. They don’t care about the suffering of the Afghans or how many people we will lose”.' ||
    '</p><p>' ||
    'That was the judgment of the highly respected anti-Taliban leader Abdul Haq, one of the many oppositionists who condemned the American bombing campaign launched in October 2001 as “a big setback” for their efforts to overthrow the Taliban from within, a goal they considered within their reach.' ||
    '</p><p>' ||
    'His judgment is confirmed by Richard A Clarke, who was chairman of the Counterterrorism Security Group at the White House under President George W Bush when the plans to attack Afghanistan were made. As Clarke describes the meeting, when informed that the attack would violate international law, “the president yelled in the narrow conference room, ‘I don’t care what the international lawyers say, we are going to kick some ass.’” The attack was also bitterly opposed by the major aid organizations working in Afghanistan, who warned that millions were on the verge of starvation and that the consequences might be horrendous.' ||
    '</p><p>' ||
    'The consequences for poor Afghanistan years later need hardly be reviewed.' ||
    '</p><p>' ||
    'The next target of the sledgehammer was Iraq.' ||
    '</p><p>' ||
    'The US-UK invasion, utterly without credible pretext, is the major crime of the 21st century. The invasion led to the death of hundreds of thousands of people in a country where the civilian society had already been devastated by American and British sanctions that were regarded as “genocidal” by the two distinguished international diplomats who administered them, and resigned in protest for this reason. The invasion also generated millions of refugees, largely destroyed the country, and instigated a sectarian conflict that is now tearing apart Iraq and the entire region. It is an astonishing fact about our intellectual and moral culture that in informed and enlightened circles it can be called, blandly, “the liberation of Iraq”.' ||
    '</p><p>' ||
    'Pentagon and British Ministry of Defense polls found that only 3% of Iraqis regarded the US security role in their neighborhood as legitimate, less than 1% believed that “coalition” (US-UK) forces were good for their security, 80% opposed the presence of coalition forces in the country, and a majority supported attacks on coalition troops. Afghanistan has been destroyed beyond the possibility of reliable polling, but there are indications that something similar may be true there as well. Particularly in Iraq the United States suffered a severe defeat, abandoning its official war aims, and leaving the country under the influence of the sole victor, Iran.' ||
    '</p><p>' ||
    'The sledgehammer was also wielded elsewhere, notably in Libya, where the three traditional imperial powers (Britain, France and the US) procured security council resolution 1973 and instantly violated it, becoming the air force of the rebels.' ||
    '</p><p>' ||
    'The effect was to undercut the possibility of a peaceful, negotiated settlement; sharply increase casualties (by at least a factor of 10, according to political scientist Alan Kuperman); leave Libya in ruins, in the hands of warring militias; and, more recently, to provide the Islamic State with a base that it can use to spread terror beyond.' ||
    '</p><p>' ||
    'Quite sensible diplomatic proposals by the African Union, accepted in principle by Libya’s Muammar Gaddafi, were ignored by the imperial triumvirate, as Africa specialist Alex de Waal reviews. A huge flow of weapons and jihadis has spread terror and violence from west Africa (now the champion for terrorist murders) to the Levant, while the Nato attack also sent a flood of refugees from Africa to Europe.' ||
    '</p><p>' ||
    'Yet another triumph of “humanitarian intervention”, and, as the long and often ghastly record reveals, not an unusual one, going back to its modern origins four centuries ago.' ||
    '</p></section>' ||
    '<footer>' ||
    'Noam Chomsky is an American linguist, philosopher, cognitive scientist, historian, social critic, and political activist. Sometimes called "the father of modern linguistics", Chomsky is also a major figure in analytic philosophy and one of the founders of the field of cognitive science.' ||
    '</footer>',
    '2021-06-05'
);

